ALTER TABLE usr
    ADD img_id BIGINT;
ALTER TABLE usr
    ADD CONSTRAINT fk_img_id FOREIGN KEY (img_id) REFERENCES image (id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE motorcycle
    ADD img_id BIGINT;
ALTER TABLE motorcycle
    ADD CONSTRAINT fk_img_id FOREIGN KEY (img_id) REFERENCES image (id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE brand
    ADD img_id BIGINT;
ALTER TABLE brand
    ADD CONSTRAINT fk_img_id FOREIGN KEY (img_id) REFERENCES image (id) ON UPDATE CASCADE ON DELETE CASCADE;